### ISSUE TITLE
[Project 2-1] System_Call (chwangmin)

### ISSUE THREAD

**Issue by chwangmin** [Blue-club/pintos_5#15]
# System_Call📞
## ✍과제 미션
- 먼저 파싱하기.
- 시스템 콜 핸들러 및 시스템 콜(halt, exit, create, remove) 구현

## 📖개념
- 시스템 콜 - 운영 체제가 제공하는 서비스에 대한 프로그래밍 인터페이스
- 사용자모드에서 커널 기능을 사용하기 위해 씀.
- 시스템 콜은 커널 모드에서 실행되고 처리 후 사용자 모드로 복귀.

### <devices/shutdown.h>
- void shutdown_power_off(void)
### <threads/thread.h>
- void thread_exit(void)
### <filesys/filesys.h>
- bool filesys_create(const char *name, off_t initial_size)
- bool filesys_Remove(const char *name)

### userprog/syscall.c
- [x] void halt(void) - pintos 종료
- [x] void exit(int status) - 스레드 종료
- [x] bool create(const char *file, unsigned initial_size) - 파일 생성
- [x] bool remove(const char *file) - 파일 제거
- [x] void check_address(void *addr) - 유저 영역에서 사용되는 유저 값인지 확인
- [x] void get_argument(void *esp, int *arg, int count) - 유저 스택에 있는 인자들을 커널에 저장하는 함수

### threads/thread.h (프로세스 디스크립터에 정보 추가)
- [x] 부모 프로세스의 디스크립터
- [x] 자식 리스트 element
- [x] 자식 리스트
- [x] 프로세스의 프로그램 메모리 적재 
- [ ] 프로세스가 종료 유무 확인 (이것이 exit 호출시 종료 status 인것 같아요.)
- [x] exit 세마포어
- [x] load 세마포어
- [x] exit 호출 시 종료 status

### threads/thread.c 
- `init_thread`(스레드 생성 시 자식 리스트 초기화) 
 list_push_back (&all_list, &t->allelem);
~
- [x] 자식 리스트 초기화
- `thread_exit`
list_remove (&t->allelem);
~
- [x] 프로세스 디스크립터에 프로세스 종료를 알리
- [x] 부모프로세스의 대기 상태 이탈(세마포어 이용)
- `thread_create` (생성된 프로세스 디스크립터의 정보를 초기화, 부모 프로세스의 자식 리스트에 추가)
- [ ] 부모 프로세스 저장
- [ ] 프로그램이 로드되지 않음
- [ ] 프로세스가 종료되지 않음
- [ ] exit 세마포어 0으로 초기화
- [ ] load 세마포어 0으로 초기화
- [x] 자식 리스트에 추가
- [ ] Add to run queue
~
thread_unblock (t);

### userprog/process.c
- `thread *get_child_process` (pid가 없을 경우 NULL 반환)
- [x] 자식 리스트에 접근하여 프로세스 디스크립터 검색
- [x] 해당 pid가 존재하면 프로세스 디스크립터 반환
- [x] 리스트에 존재하지 않으면 NULL 리턴

- `remove_child_process -> process_wait` (프로세스 디스크립터 메모리 해제)
- [x]  자식 리스트에서 제거
- [ ] 프로세스 디스크립터 메모리 해제

- `process_wait` (프로세스 정보를 알기 위해 프로세스 디스크립터 검색)
- [ ] 자식 프로세스의 프로세스 디스크립터 검색
- [x] 예외 처리 발생시 -1 리턴
- [x] 자식프로세스가 종료될 때까지 부모 프로세스 대기(세마포어 이용)
- [ ] 자식 프로세스 디스크립터 삭제
- [x] 자식 프로세스의 exit status 리턴

### userprog/syscall.*
- [x] pid_t exec(const *cmd_line) 구현 (자식 프로세스를 생성하고 프로그램을 실행시키는 시스템 콜
- [x] wait

---

exec, wait 이외 구현

**Comment by chwangmin** [comment]
### /include/lib/user/syscall.h
![image](https://github.com/Blue-club/pintos_5/assets/44563065/133d9d4a-9d22-4aca-b134-b4723a585ae9)

**Comment by chwangmin** [comment]
## #define USERPROG를 안해줘도 됨

- pintos 테스트할때 USERPROG를 알아서 정의를 해줘서 그 #ifdef USERPROG 이 실행됨.
- thread.h 에만 #define USERPROG만 해주면 되는 줄 알았는데 안해줘도 됨 


- thread.h
- thread.c
- init.c
- interrupt.c
- 그외 있을수도

**Comment by chwangmin** [comment]
### 파싱 테스트 성공
![image](https://github.com/Blue-club/pintos_5/assets/44563065/973224d8-2062-4ed8-ad34-eef0779ab135)
### 테스트 블로그 출처들
https://github.com/youngcheon/pintos-lab/blob/426305718129de6b388e96d6f03468b5aca3c7af/userprog/process.c
https://d-cron.tistory.com/60
(args) 가 안나옴 확인중..
https://woonys.tistory.com/entry/PintOS-Project-2-User-Program-2-Command-Line-Parsing63%EC%9D%BC%EC%B0%A8
### 그 외 공부
- 명령어 해설
> pintos --fs-disk=10 -p tests/userprog/args-single:args-single -- -q -f run 'args-single onearg"

물론 이렇게만 바꾸면, 이번 테스트에서만 10MB 크기의 가상 디스크를 임시로 만들어 활용할 수도 있다. 이렇게 하면 위에서와는 달리 pintos-mkdisk 명령어를 통해 가상 디스크를 만들어주지 않아도 테스트를 진행할 수 있다.  
https://codable.tistory.com/23


### 테스트 명령어
```bash
pintos --fs-disk=10 -T 10 -p tests/userprog/args-single:args-single -- -q -f run 'args-single onearg'
```
- T 10 을 주면 10초 뒤에 TIMEOUT 하는 부분이 맞는듯 (정인님 미안 !)
### TIMEOUT이 뜬 후 터미널에서 입력한 문자가 안보인다면
```bash
stty echo
```
을 치면 다시 나옵니다.

### rsp 주소 값을 찾아 확인하기
```c
printf("\n abcd~~ abcd~~~ 0x%02X \n", *(uint16_t **)rsp);
```

**Comment by mywnajsldkf** [comment]
오~ 최창광민

**Comment by doragimoochim** [comment]
오~ 최창광민

**Comment by wnstn819** [comment]
열~ 최창광민

**Comment by chwangmin** [comment]
# 다중포인터 개념 잡기.

## VSCode 에서 메모리 확인하는 법
### Extension에서 MemoryView를 설치한다.
![1](https://github.com/Blue-club/pintos_5/assets/44563065/722147ab-f2a3-479a-8ae1-89b892d6f912)

### OUTPUT, TERMINAL가 있는 칸에 MEMORY가 생긴다.
![2](https://github.com/Blue-club/pintos_5/assets/44563065/59b3308d-a567-4a99-ae32-0b100bae9c73)

### 디버깅을 하여 원하는 값의 주소를 찾는다.
![3](https://github.com/Blue-club/pintos_5/assets/44563065/e767932f-b8bc-46cf-9ea6-f2b58d108b1b)

### 주소값을 복사한 후 Ctrl + Shift + P를 사용해서
![4](https://github.com/Blue-club/pintos_5/assets/44563065/013534a3-c1ed-430f-98a0-212b7b2fbd39)

### 이 곳에 복붙하면 그 메모리 주소의 값을 확인할 수 있다.
![5](https://github.com/Blue-club/pintos_5/assets/44563065/fd854a1f-96cb-42c4-a624-3e984f672d6c)

![6](https://github.com/Blue-club/pintos_5/assets/44563065/64dbcd6b-2808-42f4-b210-2d38d06f9ade)

**Comment by chwangmin** [comment]
# system call handler 추가 구현하기
이 부분에 (args)가 출력되게 하면 될듯함
![image](https://github.com/Blue-club/pintos_5/assets/44563065/943f2e5a-7c8c-4901-993d-118629cef58e)

![image](https://github.com/Blue-club/pintos_5/assets/44563065/880a03dc-e486-4db9-bdd2-7edbe884a944)

**Comment by chwangmin** [comment]
## 세마포어 관련 함수 
![image](https://github.com/Blue-club/pintos_5/assets/44563065/deaab7fc-6626-41ac-8d69-50d449d43c69)

## ?
![image](https://github.com/Blue-club/pintos_5/assets/44563065/08da48fa-4f7c-4fdc-bc1f-988d25be8936)
